# Generated by Django 5.0.1 on 2026-02-22 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=50)),
                ('layers', models.CharField(choices=[('1', '1 Layer'), ('2', '2 Layers'), ('3', '3 Layers')], default='1', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('flavor', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='customizations/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_ons', models.ManyToManyField(blank=True, to='products.addonitem')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.cake')),
            ],
        ),
    ]
