# Generated by Django 5.0.1 on 2026-03-23

from django.db import migrations, models


def backfill_action_type(apps, schema_editor):
    UserActionLog = apps.get_model('audit', 'UserActionLog')

    def infer_action_type(action_text):
        action_text = (action_text or '').lower()
        create_keywords = ['create', 'created', 'add',
                           'added', 'new', 'register', 'registered']
        read_keywords = ['view', 'viewed', 'list', 'listed',
                         'read', 'search', 'searched', 'open', 'opened']
        update_keywords = ['update', 'updated', 'edit', 'edited', 'change',
                           'changed', 'confirm', 'confirmed', 'pay', 'paid', 'checkout']
        delete_keywords = ['delete', 'deleted',
                           'remove', 'removed', 'cancel', 'cancelled']

        if any(keyword in action_text for keyword in create_keywords):
            return 'CREATE'
        if any(keyword in action_text for keyword in read_keywords):
            return 'READ'
        if any(keyword in action_text for keyword in delete_keywords):
            return 'DELETE'
        if any(keyword in action_text for keyword in update_keywords):
            return 'UPDATE'
        return 'OTHER'

    for log in UserActionLog.objects.all().only('id', 'action', 'action_type'):
        log.action_type = infer_action_type(log.action)
        log.save(update_fields=['action_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), (
                'DELETE', 'Delete'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.RunPython(backfill_action_type, migrations.RunPython.noop),
    ]
