# Generated by Django 5.0.1 on 2026-03-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_useractionlog_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractionlog',
            name='action_type',
        ),
    ]
