# Generated by Django 5.0.1 on 2026-02-25 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_booking_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_customer_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
