# Generated by Django 5.0.1 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_galleryphoto_image"),
        ("orders", "0004_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="package_add_ons",
            field=models.ManyToManyField(
                blank=True, related_name="cart_items", to="products.addonitem"),
        ),
    ]
