# Generated by Django 5.0.1 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_cartitem_package_add_ons"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="package_inclusion_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="package_inclusion_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
