# Generated by Django 5.0.1 on 2026-02-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cake',
            name='season_tags',
            field=models.ManyToManyField(blank=True, to='products.seasontag'),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='season_tags',
            field=models.ManyToManyField(blank=True, to='products.seasontag'),
        ),
    ]
