# Generated by Django 5.0.1 on 2026-02-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_eventcategory_eventpackage_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpackage',
            name='category',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
