# Generated by Django 5.0.1 on 2026-02-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_eventpackage_category_delete_eventcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='eventpackage',
            options={'ordering': ['category__name', 'package_set', 'package_number', 'name']},
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='duration_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='inclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='package_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='package_set',
            field=models.CharField(default='General Set', max_length=100),
        ),
        migrations.AddField(
            model_name='eventpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='products.eventcategory'),
        ),
    ]
