# Generated by Django 5.0.1 on 2026-02-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_eventcategory_alter_eventpackage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.CharField(default='General', max_length=100)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.eventpackage')),
            ],
            options={
                'ordering': ['item_group', 'item_name'],
            },
        ),
    ]
