# Generated by Django 5.0.1 on 2026-02-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_packages/'),
        ),
    ]
