# Generated by Django 5.0.1 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_eventpackage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(
                blank=True, null=True, upload_to='gallery/'),
        ),
    ]
