# Generated by Django 5.0.1 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_galleryphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpackageitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10),
        ),
    ]
